#!/bin/bash

GIT=$(which git) 2> /dev/null

if [ $? == 0 ];
then
   echo "git is installed."
else
   echo You may want to try installing git.
   exit 1
fi

if [ -d "../vagrant-tools" ];
then
	cd ../vagrant-tools
	git pull
        echo 1
        sleep 5
        # We are cloning ghost here to facilitate development for the developers. This is very important.
        if [ -d ghost-vagrant ];
        then
           echo 2
           sleep 5
           echo "All good"
           cd ghost-vagrant
           git pull
           cd -
        else
           echo 3
           sleep 5
           git clone http://git.publiodigital.com/ghost-themes/ghost-core.git ghost-vagrant
        fi
else
   git clone http://git.publiodigital.com/Infrastructure/vagrant-tools.git ../vagrant-tools
   cd ../vagrant-tools
   # We are cloning ghost here to facilitate development for the developers. This is very important.
   if [ -d ghost-vagrant ];
   then
     echo 4
     sleep 5
     echo "All good"
     cd ghost-vagrant
     git pull
     cd -
   else
     echo 5
     sleep 5
     git clone http://git.publiodigital.com/ghost-themes/ghost-core.git ghost-vagrant
   fi
fi

git checkout local_dev
git pull

echo "I am going to rebuild vagrant machine for you"

VAGRANT_DIR=".vagrant"

if [ -f Vagrantfile ]
then
   echo "Proceeding since vagrant file is available";
else
   echo "git clone may have failed"
   exit 1
fi


if [ -d ${VAGRANT_DIR} ];
then
   echo "Looks like the virtual machine is already on!"
   echo "Do you want to start clean. if yes, press y else press n"
   read input
   if [ $input == "y" ];
   then
      vagrant destroy -f
      vagrant up
      vagrant reload --provision
   elif [ $input == "n" ];
   then
	   vagrant reload --provision
   else
      echo "I dont understand your input."
      exit 1
   fi
else
   vagrant up
   vagrant reload --provision
fi

if [ $? == 0 ];
then
   vagrant ssh
else
   echo "ERROR: Looks like something went wrong!!!!"
   exit 1
fi

